Repository fdm-monster/fdm-monster, pull requests merged in 2024-11, with the labels that each got.

#3168 Support Moonraker and therefore Klipper
  .gitignore
  RELEASE_NOTES.MD
  package.json
  src/controllers/server-public.controller.ts
  src/controllers/settings.controller.ts
  src/controllers/validation/printer-controller.validation.ts
  src/middleware/printer.ts
  src/server.constants.ts
  src/services/core/yaml.service.ts
  src/services/moonraker.api.ts
  src/services/moonraker/moonraker.client.ts
  src/services/octoprint/dto/octoprint-event.dto.ts
  src/services/octoprint/utils/file.utils.ts
  src/services/printer-api.factory.ts
  src/services/printer-api.interface.ts
  src/services/socket.factory.ts
  src/services/validators/printer-service.validation.ts
  src/services/validators/yaml-service.validation.ts
  src/state/printer-events.cache.ts
  src/state/printer.cache.ts
  test/api/printer-controller.test.ts
  test/api/settings-controller.test.ts
  test/application/store/files-store.test.ts
  test/test-server.ts
  yarn.lock
Labels: epic

#3711 Fix/moonraker no api key
  RELEASE_NOTES.MD
  src/controllers/validation/printer-controller.validation.ts
  src/entities/printer.entity.ts
  src/models/Printer.ts
  src/services/validators/printer-service.validation.ts
  src/tasks/printer-websocket-restore.task.ts
  test/api/printer-controller.test.ts
Labels: bug, klipper

#3727 Fix/3725 octoprint state poll repeatedly null
  RELEASE_NOTES.MD
  requests/octoprint/octoprint-api-printer-current.http
  requests/octoprint/octoprint-pluginmanager-plugins.http
  src/container.tokens.ts
  src/container.ts
  src/services/octoprint/dto/printer/current-printer-state.dto.ts
  src/services/octoprint/dto/websocket/current-message.dto.ts
  src/services/octoprint/octoprint-api.routes.ts
  src/services/octoprint/octoprint-websocket.adapter.ts
  src/services/octoprint/octoprint.client.ts
  src/state/printer-events.cache.ts
  src/tasks.ts
  src/tasks/printer-state-update-poll.task.ts
Labels: bug

#3729 (build) fix docker file annotation
  docker/Dockerfile
  docker/alpha.Dockerfile
  docker/test.Dockerfile
Labels: bug, docker

#3735 fix: docker packages for arm64 should track latest, 1.x etc not separate latest-arm64 (etc) tag
  .github/workflows/docker_alpha_build.yml
  .github/workflows/docker_arm64_build.yml
  .github/workflows/docker_release.yml
  build.ps1
  docker/sqlite.Dockerfile
  src/server.constants.ts
Labels: bug

#3755 fix: adjust max length of apiKey property validation to 43 to allow new `secrets` based OctoPrint api keys
  RELEASE_NOTES.MD
  package.json
  src/constants/service.constants.ts
  src/controllers/validation/printer-controller.validation.ts
  src/models/Printer.ts
  src/server.constants.ts
  src/services/validators/printer-service.validation.ts
  src/services/validators/yaml-service.validation.ts
  src/state/validation/create-test-printer.validation.ts
  test/api/printer-controller.test.ts
  yarn.lock
Labels: bug

#3762 fix: catch null or undefined id before querying database
  RELEASE_NOTES.MD
  src/services/orm/base.service.ts
  test/application/user-service.test.ts
Labels: bug

#3794 fix: demo mode should never show first-time-setup
  src/controllers/auth.controller.ts
Labels: bug

#3796 fix: incorrect UI state "No USB" shown, when OctoPrint USB is disconnected
  RELEASE_NOTES.MD
  src/services/octoprint/octoprint-websocket.adapter.ts
Labels: bug
